### PR TITLE
Center preferences stage on main stage

### PR DESCRIPTION
**Pull request by AustinShalit**
Inspired by https://github.com/wpilibsuite/OutlineViewer/pull/57

### CODE REVIEW

**Comment by AustinShalit** [comment]
@nightpool or @SamCarlberg Do you know why tests are failing?

**Comment by SamCarlberg** [comment]
I think this is one of those spurious tests.

Can you please make these changes for the plugins dialog as well?

**Comment by bradamiller** [comment]
@AustinShalit are you done with this? It says it fails on jenkins. Is that test a valid error or is the test broken?

**Comment by JLLeitschuh** [comment]
Looks good now.

**Pull request merged**
