### PR TITLE
Fix Jenkins

### PR DESCRIPTION
**Pull request by AustinShalit**
Supports the closure of #205

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Why not use a junit 5 tag annotation on this test that disables it on Jenkins? That way it still runs on Travis CI?

**Comment by AustinShalit** [comment]
This is the exception we get on Jenkins:
```
Failures (1):
  JUnit Jupiter:WidgetSaverTest:loadSimpleWidget()
    MethodSource [className = 'edu.wpi.first.shuffleboard.app.json.WidgetSaverTest', methodName = 'loadSimpleWidget', methodParameterTypes = '']
    => java.lang.RuntimeException: Unable to invoke no-args constructor for interface edu.wpi.first.shuffleboard.api.widget.Widget. Registering an InstanceCreator with Gson for this type may fix this problem.
```

**Comment by JLLeitschuh** [comment]
What version of the JDK is Jenkins running?

**Comment by AustinShalit** [comment]
It is running 1.8.0_144.  No idea if it is Oracle or Open.  The weird part is if I build it manually on my user account, it runs fine.  It is only when Jenkins runs that specific test it fails.

**Comment by JLLeitschuh** [comment]
Cosmic rays?
It could be a line ending thing?

**Comment by AustinShalit** [comment]
Progress update, the build now fails like this:
```
DoubleProperty [bean: edu.wpi.first.shuffleboard.app.json.WidgetSaverTest$SimpleWidget@32ec9c90, name: min, value: 0.0]
DoubleProperty [bean: edu.wpi.first.shuffleboard.app.json.WidgetSaverTest$SimpleWidget@32ec9c90, name: max, value: 0.0]
DoubleProperty [bean: edu.wpi.first.shuffleboard.app.json.WidgetSaverTest$SimpleWidget@32ec9c90, name: blockIncrement, value: 0.0]
Oct 01, 2017 10:58:28 PM edu.wpi.first.shuffleboard.app.plugin.PluginLoader load
INFO: Loading plugin test.Mock Plugin-v0.0.0

Failures (1):
  JUnit Jupiter:WidgetSaverTest:loadSimpleWidget()
    MethodSource [className = 'edu.wpi.first.shuffleboard.app.json.WidgetSaverTest', methodName = 'loadSimpleWidget', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <-1.0> but was: <0.0>
```

**Comment by AustinShalit** [comment]
Just tested again by SSHing into Jenkins, cloning this branch, and running `./gradlew check -Pheadless`.  The build passes, and my prints are correct....

```DoubleProperty [bean: edu.wpi.first.shuffleboard.app.json.WidgetSaverTest$SimpleWidget@32ec9c90, name: min, value: 0.0]
DoubleProperty [bean: edu.wpi.first.shuffleboard.app.json.WidgetSaverTest$SimpleWidget@32ec9c90, name: max, value: 0.0]
DoubleProperty [bean: edu.wpi.first.shuffleboard.app.json.WidgetSaverTest$SimpleWidget@32ec9c90, name: blockIncrement, value: 0.0]
Oct 01, 2017 10:58:28 PM edu.wpi.first.shuffleboard.app.plugin.PluginLoader load
INFO: Loading plugin test.Mock Plugin-v0.0.0

Failures (1):
  JUnit Jupiter:WidgetSaverTest:loadSimpleWidget()
    MethodSource [className = 'edu.wpi.first.shuffleboard.app.json.WidgetSaverTest', methodName = 'loadSimpleWidget', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <-1.0> but was: <0.0>```

**Comment by AustinShalit** [comment]
@frcjenkins retest this please

**Comment by JLLeitschuh** [comment]
> `System.lineSeparator()`

ROFOL. I can't believe that's actually what's causing this.

I would complain to gson about this. Ask if anyone on that team has any thoughts.

**Comment by AustinShalit** [comment]
No, that was me trying to fix it.

**Comment by nightpool** [comment]
+1

**Pull request merged**
