### PR TITLE
Enable saving docker images in the travis cache

### LINKED ISSUE #222: Cache the Travis Docker Image to speed up builds
Related to #220 

The travis Docker image is built every time the CI system runs.
This adds about 80 seconds or so to the builds. This could be reduced if we took advantage of uploading docker containers or using travis's caching mechanism.

Example of how one user figured out how to cache docker containers in travis without uploading them to docker hub:
https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Closes #222

Current build time without caching: `Ran for 6 min 5 sec`

### CODE REVIEW

**Comment by PeterJohnson** [comment]
The linked GitHub comment talks about a --cache-from command line option to avoid these workarounds.  Is that not available yet?

**Comment by JLLeitschuh** [comment]
I haven't seen a solid application of that solution. This solution doesn't seem to be working either though.

**Comment by JLLeitschuh** [comment]
Yo, @SamCarlberg can you merge this up with master for me and see if it still works? It will probably speed up your Travis builds.

**Comment by SamCarlberg** [comment]
The first build after updating took 8:58, second build 11:03, and the third build errored out after 9 minutes:

```bash
$ docker run -it $ci_env -v ${GRADLE_CACHES}:${DOCKER_GRADLE_CACHES} shuffleboard-devel ./.travis.ubuntu.sh
+ export DISPLAY=:99
+ DISPLAY=:99
+ ./gradlew --version --console=plain
+ Xvfb :99
Unzipping /root/.gradle/wrapper/dists/gradle-4.1-bin/c3kp51zwwt108wc78u68yt7vs/gradle-4.1-bin.zip to /root/.gradle/wrapper/dists/gradle-4.1-bin/c3kp51zwwt108wc78u68yt7vs
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:215)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:75)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

This does not seem to be stable, and when it does work build times are a few minutes longer, probably due to cache timeouts: 
```
attempting to download cache archive
fetching PR.223/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--jdk-oraclejdk8.tgz
running `casher fetch` took longer than 180 seconds and has been aborted.
```

**Comment by ThadHouse** [comment]
With the change to azure, with is obsolete, right?

**Comment by JLLeitschuh** [comment]
Yes

**Pull request closed without merging**
