### PR TITLE
Add encoding to javadoc task so it doesn't crash on utf-8 chars

### LINKED ISSUE #658: published API Javadoc jar is empty
The javadoc jar published at https://frcmaven.wpi.edu/artifactory/release/edu/wpi/first/shuffleboard/api/2020.3.2/ is empty

### PR DESCRIPTION
**Pull request by AustinShalit**
Closes #658 

# Overview

# Screenshots

### CODE REVIEW

**Comment by AustinShalit** [comment]
Download artifacts here for testing: https://dev.azure.com/wpilib/DesktopTools/_build/results?buildId=11636&view=artifacts&type=publishedArtifacts

**Comment by SamCarlberg** [comment]
Nice. Can you also publish the docs for the plugins?

I've also noticed the docs don't link to the JDK or JavaFX classes. That should be fixed, but I don't think it's necessary for this PR

**Comment by AustinShalit** [comment]
>Nice. Can you also publish the docs for the plugins?

Yes

>I've also noticed the docs don't link to the JDK or JavaFX classes. That should be fixed, but I don't think it's necessary for this PR

Yea... I can fix that later

**Comment by sciencewhiz** [comment]
The search doesn't work. Probably needs same patch as allwpilib/docs

**Pull request closed without merging**
