### PR TITLE
Set the main window title to "Shuffleboard"

### LINKED ISSUE #130: No Title
The main window does not have a title.

### PR DESCRIPTION
**Pull request by SamCarlberg**
Closes #130

### CODE REVIEW

**Comment by AustinShalit** [comment]
This would be a nice place to cheat and also close the connection indicator issue until we have time for a better solution.

**Comment by SamCarlberg** [comment]
As I said in #54, that's too subtle and easy to miss. It also doesn't work for undecorated or fullscreen

**Comment by nightpool** [comment]
I thought we decided we weren't calling things "Shuffleboard"?

**Comment by JLLeitschuh** [comment]
You do have all the code in a file called `edu.wpi.first.shuffleboard.app.Shuffleboard.java`. I see "Shuffleboard" in there twice.

**Comment by JLLeitschuh** [comment]
I'm impartial, you should open an issue about naming and vote on different ideas, similar to: https://github.com/gradle/kotlin-dsl/issues/182

**Pull request merged**
