### PR TITLE
Set initial window size to screen's visual bounds

### PR DESCRIPTION
**Pull request by calcmogul**
This prevents my computer's task bar from covering the window decorations and
tab list.

### CODE REVIEW

**Comment by SamCarlberg** [comment]
This would break for people with multiple screens with different resolutions, like plugging in a macbook to an iMac as a secondary display.

I wouldn't be against binding the maximum width and height to the size of the current display, but that would run into issues when dragging the window between two screens with different resolutions

**Comment by calcmogul** [comment]
Perhaps we could give the window a sane default size, like the size of the current display, and not set a minimum or maximum.

**Comment by AustinShalit** [comment]
@calcmogul - How does the window get that large? Does it start that way?

**Comment by calcmogul** [comment]
Yes. Since the size specified in the XML is infinite, the window maximizes the window area to my whole screen, which also hides the window decorations. My taskbar then covers the tab list. I use the Xfce desktop environment.

**Comment by SamCarlberg** [comment]
The _maximum_ size is infinite, but the default size should be based on the size of the components in the window.

Are you using a high DPI display? I know JavaFX has issues with DPI scaling on Linux.

**Comment by calcmogul** [comment]
For some reason, shuffleboard starts at the maximum size. I've changed `maxWidth` and `maxHeight` in MainWindow.fxml to verify this is the case. My display is 1366x768, so definitely not high DPI.

**Comment by nightpool** [comment]
We definitely don't want to be overriding the WMs standard behavior here. I think #55 fixes the pain point here in a less obtrusive way (see e01ea08)

**Comment by AustinShalit** [comment]
Does #55 fix the issue this PR was trying to solve @calcmogul?

**Comment by calcmogul** [comment]
No. The width is sane now, but the window is still too tall.

**Pull request closed without merging**
