### PR TITLE
README: How to set JAVA_HOME if JDK 9 is installed

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Related: #293

### CODE REVIEW

**Comment by SamCarlberg** [comment]
What about Windows?

**Comment by JLLeitschuh** [comment]
I think you have to do some wackiness with the environment variables through the UI.

When I was working on WPILib I used this tool which was 100% better than the one that was built into Windows 7.
http://eveditor.com/

**Comment by SamCarlberg** [comment]
FWIW Windows 10 has a _much_ better environment variable editor then previous versions of Windows. 

It may be possible to use `set` to change `PATH` an `JAVA_HOME` in a local command session without affecting the actual environment variables. It'd be tricky, though. Ugh.

**Comment by sciencewhiz** [comment]
does java -Djava.home=PATH work? That would be cross platform

**Comment by JLLeitschuh** [comment]
No, that wouldn't work. You need to have `$JAVA_HOME` set for gradle to be executed with the right version. Look at the code inside of the `gradlew` file.

**Comment by JLLeitschuh** [comment]
Anyone want to merge this??

**Comment by JLLeitschuh** [comment]
@SamCarlberg Do you want me to close this?

**Comment by SamCarlberg** [comment]
I think so, now that we display a warning dialog and prevent launching when not running on Java 8

**Pull request closed without merging**
