### PR TITLE
Allow checking for and applying updates from the FRC maven server

### PR DESCRIPTION
**Pull request by SamCarlberg**
Shuffleboard will check for updates at startup by parsing `http://first.wpi.edu/FRC/roborio/maven/release/edu/wpi/first/shuffleboard/app/maven-metadata.xml` for the newest version, then prompt the user to download it. The jar is downloaded to a temp file, then copied and overwrites the original jar file after shutdown, then finally restarted.

This PR allows shuffleboard to update at its own pace without being tied to the update schedule of the Eclipse plugins.

Users can disable the check at startup in the application settings, and can check for updates at any time with the menu item `File -> Check for updates` or with Ctrl+U  or ⌘+U

### CODE REVIEW

**Comment by SamCarlberg** [comment]
@AustinShalit Here's the reasoning behind this PR:

- Shuffleboard is still new, and new features and bugfixes are likely to get merged
- Only bundling shuffleboard releases in the Eclipse plugins means that releases are limited, which means that bugfixes and new features don't get distributed quickly (see #370, which had a fix merged a _week_ prior, but hasn't been released yet since there hasn't been a plugins release)
- The Eclipse plugins will always have the most up-to-date version at the time they're created. Shuffleboard may have had updates since then, which users would not be able to use without
  - manually checking the Maven server; or
  - opening an issue for a bugfix or feature request that has already been added in a more recent release, then having one of us point them to the new release
- Shuffleboard will not automatically update; that is _always_ up to the user. All it does is notify the user that a newer version is available, and provides an easy method for download and installation.
- Users don't have to keep track of anything special for shuffleboard. There is no standalone installer like NI or CTRE. As I said above, it's all in one jar file that comes with the WPILib Eclipse plugins.

I don't see any fracturing here. The only potential issue I can see is that having a specific version of the plugins does not guarantee a specific version of shuffleboard. I don't think that's a problem, since a new install will always have the same version, and the shuffleboard version is very easily checked

**Comment by bradamiller** [comment]
It's important that the version number always increments. Also, are you covering the case where someone installs a newer version of shuffleboard, then installs an older version of the plugins? I assume that shuffleboard will get downgraded with the plugins install, then they'll start getting messages again about upgrading it.

**Comment by SamCarlberg** [comment]
There's nothing I can do here to avoid the plugins from nuking the wpilib directory. Shuffleboard would be downgraded but would alert the user at startup (if enabled; they can always check manually with the menu).

The version number will never decrement, otherwise it breaks semantic versioning.

**Comment by SamCarlberg** [comment]
# Screenshots

## Update prompt
screenshot from 2018-01-23 10-59-45

## Download progress
screenshot from 2018-01-23 11-00-09

## Restart prompt
screenshot from 2018-01-23 11-00-21

## "About" dialog

screenshot from 2018-01-23 11-15-49

Contains

- Build version and build date
- JRE version and vendor
- Operating system name and version
- "Copy to clipboard" button for the technical information

**Comment by bot190** [comment]
There seems to be an issue with this feature. If you launch shuffleboard without an internet connection it complains that it is unable to connect to the update server. The modal that this error appears in doesn't have a way of closing it. This makes shuffleboard impossible to use without an internet connection. Something that seems extremely likely when connecting to robot wfi networks.
shuffleboardrequiresinternet

**Pull request merged**
