### PR TITLE
Use field images from allwpilib

### PR DESCRIPTION
**Pull request by pjreiniger**
# Overview
Uses the field images from the allwpilib rather than duplicating them in this repository. From now on, when the allwpilib jar is updated, shuffleboard will automatically get the update

I see the 2023 field is on its way into Pathweaver, where I plan to do the same thing

### CODE REVIEW

**Comment by sciencewhiz** [comment]
java crashes for me 

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb745691aa, pid=25152, tid=11740
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.8+10) (build 11.0.8+10)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.8+10, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x3a91aa]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Joe\Documents\Robotics\shuffleboard\app\hs_err_pid25152.log
Jan 13, 2023 8:45:40 PM edu.wpi.first.shuffleboard.app.plugin.PluginLoader load
INFO: Loading plugin edu.wpi.first.shuffleboard:CameraServer:3.1.0
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#
```

[hs_err_pid25152.log](https://github.com/wpilibsuite/shuffleboard/files/10416590/hs_err_pid25152.log)

**Comment by pjreiniger** [comment]
What's in the dump? I doubt camera server native code is getting affected by a pure java change in a separate plugin.

Looks like release prep had started so I can try again for the next release, but I can't reproduce

**Comment by pjreiniger** [comment]
Oh the dump is already attached. Will investigate with the new release

**Comment by sciencewhiz** [comment]
This works on main for me

**Review by sciencewhiz — APPROVED** [review]

**Pull request merged**
